### PR TITLE
updated requirements pinning to only necessary packages

### PR DESCRIPTION
**Pull request by stets**
The previous pip freeze introduced some trouble:

- pip freeze saves all packages in the environment including even those that you don't use in your current project.

I've used the `pipreqs` library to generate only the necessary packages, they are also in line with the requirements @cc-d  generated earlier

more info 
https://dev.to/bhupesh/pipreqs-automatically-generate-python-dependencies-30nl
https://medium.com/@tomagee/pip-freeze-requirements-txt-considered-harmful-f0bce66cf895

ref https://github.com/cc-d/ieddit/issues/22

### CODE REVIEW

**Comment by cc-d** [comment]
Honestly, I should be using virutalenvs. I usually only run 1 python app per system so it was never very important to me. That being said, the requirements list that was generated will not provide full site functionality, only the stripped down site version which can easily be setup locally.

Flask-Limiter==1.0.1
Flask-Session==0.3.1
flask-session-captcha==1.1.0
Flask-Sessionstore==0.4.5

Are some packages omitted which will cause issues. Sessions, ratelimiting, captcha. They aren't technically required to run the bare minimum of the site, but any development in those areas will require them.

I'll merge this and then specifically re-add the packages I know extended site functionality will need.

**Comment by cc-d** [comment]
I do not have easy access to other environments to test this currently.

Could you strip out the bare minimum packages which are causing errors, and see if everything still works?

In config.py, changing Captcha=True and RateLimit=True will enable the functionality the previous requirement list left out.

**Comment by cc-d** [comment]
Also, I'll check out the tool you linked. I might be able to generate a requirements list that covers all functionality while stripping out the extra packages.

**Comment by stets** [comment]
>Flask-Limiter==1.0.1
Flask-Session==0.3.1
flask-session-captcha==1.1.0
Flask-Sessionstore==0.4.5
 

>Are some packages omitted which will cause issues. Sessions, ratelimiting, captcha. They aren't technically required to run the bare minimum of the site, but any development in those areas will require them.

`Flask_Limiter` is present, although the formatting is different. I'm not sure why this discrepancy is present.

`flask_session_captcha` is present, although also formatted different as above is.

`Flask_Session==0.3.1` has the same issue as above. Formatted with hyphens instead of quotes.

`Flask-Sessionstore` is installed as a dependency of flask-sessionstore



@cc-d

**Comment by stets** [comment]
Ok, here's some more insight

>Using a project name with dashes will make your plugin installable with pip. Pip replaces underscores with dashes, so if you use underscores in the project name it will not work.

via https://pybuilder.github.io/documentation/external_plugins.html#.XZPyPOdKjOQ

So they are the same, but dashes are preferred.

**Comment by cc-d** [comment]
Gotcha. Thanks for the info.

**Comment by cc-d** [comment]
Sorry for allowing my ignorance to cause problems here :)

**Comment by stets** [comment]
> Sorry for allowing my ignorance to cause problems here :)

np -- you'll need psycopg2 in requirements as well :-)

**Pull request merged**
