### PR TITLE
updated text wrapping issue on ios; changed nsfw to red border for some reason

### PR DESCRIPTION
**Pull request by wnewlad**
was fucking around and tried to fix the text wrapping on ios again. definitely want to test locally first. 

image
Screen Shot 2019-10-11 at 1 50 05 PM copy
Screen Shot 2019-10-11 at 1 49 58 PM copy
Screen Shot 2019-10-11 at 1 49 42 PM copy
Screen Shot 2019-10-11 at 1 49 36 PM copy

### CODE REVIEW

**Comment by wnewlad** [comment]
oh also added maxlength to some title fields

**Comment by cc-d** [comment]
that looks fucking awesome.

great all around. thanks man

**Comment by cc-d** [comment]
so there are two different types of 'delete', a user-delete, and a mod-delete. the important difference between the two is that one shows up in the modlog.

it really doesn't make any sense for a moderator's own post/comment deletions to show up in the modlog... the layout change you made here makes a ton more sense lol

**Comment by cc-d** [comment]
ok, so i had to make some changes to this.

i added checks to where the mod-delete/nsfw options would not show on the sub list pages if a user was both the author of the post, and a  mod

i really like the border change. this is better than 'nsfw' text i think

**Comment by cc-d** [comment]
there was also a trailing <\/small> which was not added unless a user was a mod, as a humorous post on  /r/ieddit now indicates :)

**Comment by cc-d** [comment]
and a <\/div> on the recent comments page that broke things lol.

i added some more commits to bring this design philosophy to the rest of the site.

**Comment by cc-d** [comment]
so for now i moved the bottom mod-options back to float-right.

the reason being potential accidental mod actions when upvoting/commenting on a post.

**Comment by wnewlad** [comment]
Ah shit my bad. I didn’t realize the double delete links were intentional- I should have looked more closely. Sorry bout that. 

I wish there was a way to hide the jinja or whatever tags in ide- makes it a pain to align the markup wrt nesting hence the bologna extra small tag (excuses excuses). 

Sorry I made a bunch of more work for you to fix shit. I’ll be more careful next time pinky swear 🙃

**Comment by cc-d** [comment]
no problem man, shit happens. i appreciate the contributions :)

**Comment by cc-d** [comment]
i like how you handled the text wrapping, plus the red borders for nsfw

**Pull request merged**
